USE labbio_admin;

ALTER TABLE mutuales
  ADD COLUMN codigos VARCHAR(255) NULL,
  ADD COLUMN apb ENUM('Paga','No paga','Mitad y mitad','Depende plan') NULL,
  ADD COLUMN apb_adicional VARCHAR(255) NULL,
  ADD COLUMN coseguros ENUM('Paga','No paga','Depende plan','Viene en la autorización') NULL,
  ADD COLUMN coseguros_adicional TEXT NULL,
  ADD COLUMN token ENUM('Solicitar','No dispone') NULL,
  ADD COLUMN autorizacion ENUM('Tiene que venir autorizado','Sin autorización','Autorizar luego') NULL,
  ADD COLUMN elegibilidad ENUM('Validar','No hace falta') NULL,
  ADD COLUMN elegibilidad_adicional TEXT NULL,
  ADD COLUMN validez INT NULL,
  ADD COLUMN planes VARCHAR(255) NULL,
  ADD COLUMN receta JSON NULL,
  ADD COLUMN domicilio_cubre ENUM('Cubre','No cubre') NULL,
  ADD COLUMN domicilio_adicional VARCHAR(255) NULL,
  ADD COLUMN credencial ENUM('Plástica','Digital','Todas') NULL,
  ADD COLUMN atencion VARCHAR(255) NULL,
  ADD COLUMN comentarios TEXT NULL,
  ADD COLUMN cuit VARCHAR(32) NULL,
  ADD COLUMN razon_social VARCHAR(255) NULL,
  ADD COLUMN factura VARCHAR(255) NULL,
  ADD COLUMN nomenclador VARCHAR(255) NULL,
  ADD COLUMN domicilio_fact VARCHAR(255) NULL,
  ADD COLUMN entrega VARCHAR(255) NULL,
  ADD COLUMN correo VARCHAR(255) NULL,
  ADD COLUMN telefonos VARCHAR(255) NULL,
  ADD COLUMN portal VARCHAR(255) NULL;
